# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: PIAT William
title: PhD student in robust statistical learning
email: william.piat3@gmail.com
website: www.github.com/williampiat3

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  williampiat3
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: william-piat-1202b2b8
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  I am currently a PhD student, making research in the fields of robust statistical learning and sensitivity analysis.
  Before this I worked in a lot of different companies with various sizes: start up companies for a more diverse and operational activity and flexible cloud computing environements, big companies with very specific knowledge in neutronics or aeronautics with computation clusters for simulations. 
  This broad background always gives me ideas for new projects that I love to share on my github.
  Feel free to contact me over one of my projects or one of my publications, I'll be happy to discuss it!


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Normandie Université - Safran
        caption: 2020 - 2023
        sub_title: PhD in Statistics and Computer science
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          “CIFRE” PhD (half academic, half industrial PhD) made in collaboration between Normandie Université and Safran.
          The goal was to develop methods for robust training and certifying technological solutions based on deep learning. 
          (Robust optimization, Wassertein distributional robustness, Lipschitz networks, Monte Carlo methods)
      - layout: left
        title: Centrale Lyon - Université Lyon 1
        caption: 2017 - 2018
        sub_title: Double diploma, Engineering diploma and Master degree
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          This double diploma was acheived during my last year of engineer school in Computer Science.
          I followed more practical courses at the university on multi agent systems, evolutionary algorithms, traditional machine learning.
      - layout: left
        title: Centrale Lyon
        caption: 2014 - 2017
        sub_title: General engineering
        # quote: >
        #   General engineering is a very French concept where is taught a bit of everything, or as some critics might say: a bit of nothing.
        description: | # this will include new lines to allow paragraphs
          Three years in a top French engineering school. These were dedicated to core courses before the selection of a specialty in last year.    
      - layout: left
        title: Henri IV - Louis Le Grand
        caption: 2012 - 2014
        sub_title: MP - PSI*
        #quote: >
        #  General engineering is a very French concept where is taught a bit of everything, or as some critics might say: a bit of nothing.
        description: | # this will include new lines to allow paragraphs
          “Classe préparatoire” Two-year intensive program preparing for the national competitive exam for entry to top French engineering schools.
          First year: MPSI in Henri IV High School; second year: PSI* in Louis le Grand High School.


      - layout: left
        title: Lycée en Forêt
        caption: 2011 - 2012
        #sub_title: 
        #quote: >
        #  General engineering is a very French concept where is taught a bit of everything, or as some critics might say: a bit of nothing.
        description: | # this will include new lines to allow paragraphs
          Baccalauréat (equivalent to A-levels) in science and maths with honours.

  - title: Skills
    layout: text
    content: | #test
      * Languages: English (Fluent), French (Native), German (Conversational), Spanish (Conversational)
      * **Statistics**: Robust optimization, Gradient methods, Gaussian processes, Markov Decision Processes, Monte Carlo methods, Uncertainty quantification, Optimal Transport.
      * **Programming**: C++, SQL, Python, R, Git, Docker
      * **Deep learning**: Pytorch (Proeficient: 6 years experience), Distributed trainings over multiple nodes of a cluster scheduled with slurm ecosystem.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Framatome
        link: https://www.framatome.com
        link_text: framatome.com
        sub_title: Research engineer
        caption: 2018 - 2020
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Using state of the art open source technologies (mostly Pytorch, but also Tensorflow) to build predictive models to simulate complex 3D nuclear core physics 
          Performing sensitivity analysis (Sobol indices, Shapley indices) by the mean of metamodeling.
          Develloping evolutionary algorithms (genetic algorithms and genetic programming) to tune complex black box models.
      - layout: left
        title: Cocoon Leasing pty

        sub_title: Process engineer/analyst
        caption: 2017 - 2018
        #quote: >
        description: | # this will include new lines to allow paragraphs
          Part time job: data engineer for an Australian Leasing company.
          Using google cloud platform to automate leasing processes (**Google compute engine, Cloud SQL, App engine**). 
      - layout: left
        title: ShopWings
        sub_title: Process engineer/analyst
        caption:  November 2016 - May 2017
        #quote: >
        description: | # this will include new lines to allow paragraphs
          6 months internship in **Australia** in a Rocket internet company.
          Automatizing current computer framework and maintenance of the databases of the company (SQL, Python, Git)

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: August 2022
        sub_title: Workshop paper
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Towards an Evaluation of Lipschitz Constant Estimation Algorithms by building Models with a Known Lipschitz Constant**. Joint work with Frédéric JURIE, Jalal FADILI and Sébastien DA VEIGA. Presents an approach to quantify the error made by Lipschitz assessing algorithms for deep neural nets.
      - layout: left
        title: June 2022
        sub_title: Submitted journal article
        #quote: >
        description: | # this will include new lines to allow paragraphs
          **Regularized Robust Optimization with Application to Robust Learning**. Joint work with Frédéric JURIE, Jalal FADILI and Sébastien DA VEIGA. Introduce a new approach to tackle Distributional Robust optimization of non-smooth functions with guarantees. Our algorithm combines smoothing with Monte Carlo sampling for and can asymptotically solve the problem.  
      
  - title: Projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      Here is the non exhaustive list of some personal projects that I worked on:
      - [Networking and types of VPN to allow seemless streaming of a gaming PC or console](https://github.com/williampiat3/ImprovingPSRemotePlay)
      - [Upscaling videos with a Wasserstein GAN and making this able to run on a potatoe](https://github.com/williampiat3/Upscale)
      - [Building genetic algorithms to optimize black box models](https://github.com/williampiat3/GeneticAlgorithm)
      - [Making a photobooth for my brother's wedding](https://github.com/williampiat3/photoBoothQ)
      - Using greedy algorithms on graph to optimize medical plannings
      - Coding an app for [sending easily Spotify musics](https://playlistsender.herokuapp.com/) to friends and to [receive them](https://playlistreceiver.herokuapp.com/)
      - [Using basical knowledge of deep reinforcement learning to minimize wait time of elevator users](https://github.com/williampiat3/Reinforcement)
  - title: Some Extra
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not working I like :
      - Every single type of ski (cross country skiing, touring skis, downhill skis).
      - Tinkering with Raspberry pis, Arduinos and 3D printing.
      - Running and mountain biking.
      - Repairing broken electronics and bikes.
      - Occasionally Kitesurfing
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
